create extension if not exists citext with schema extensions;

create table public.projects (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    name text not null,
    domain text not null,
    description text,
    created_at timestamptz not null default now(),
    unique (id, user_id)
);

create table public.chats (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    project_id bigint not null,
    title text not null,
    objective text,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (project_id, user_id)
        references public.projects(id, user_id) on delete cascade
);

create table public.messages (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    chat_id bigint not null,
    role text not null,
    type text not null,
    content text not null,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (chat_id, user_id)
        references public.chats(id, user_id) on delete cascade
);

create table public.experiment_ai_messages (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    chat_id bigint not null,
    role text not null,
    content text not null,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (chat_id, user_id)
        references public.chats(id, user_id) on delete cascade
);

create table public.audio_records (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    chat_id bigint not null,
    message_id bigint,
    file_path text not null,
    transcript text,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (chat_id, user_id)
        references public.chats(id, user_id) on delete cascade,
    foreign key (message_id, user_id)
        references public.messages(id, user_id) on delete cascade
);

create table public.summaries (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    scope text not null,
    project_id bigint,
    chat_id bigint,
    summary_style text not null default 'Standard cercetare',
    content text not null,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (project_id, user_id)
        references public.projects(id, user_id) on delete cascade,
    foreign key (chat_id, user_id)
        references public.chats(id, user_id) on delete cascade,
    check (
        (scope = 'project' and project_id is not null and chat_id is null)
        or (scope = 'chat' and chat_id is not null)
    )
);

create unique index idx_summaries_project_style
    on public.summaries(user_id, project_id, summary_style)
    where scope = 'project';
create unique index idx_summaries_chat_style
    on public.summaries(user_id, chat_id, summary_style)
    where scope = 'chat';

create table public.project_ideas (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    project_id bigint not null,
    title text not null,
    description text not null,
    evidence text,
    importance text,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (project_id, user_id)
        references public.projects(id, user_id) on delete cascade
);

create table public.mindmap_nodes (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    project_id bigint not null,
    node_key text not null,
    label text not null,
    description text,
    importance text,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    unique (user_id, project_id, node_key),
    foreign key (project_id, user_id)
        references public.projects(id, user_id) on delete cascade
);

create table public.mindmap_edges (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    project_id bigint not null,
    source_key text not null,
    target_key text not null,
    relation text,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (project_id, user_id)
        references public.projects(id, user_id) on delete cascade
);

create table public.mindmap_source_state (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    project_id bigint not null,
    source_type text not null,
    source_id bigint not null,
    content_hash text not null,
    processed_at timestamptz not null default now(),
    unique (id, user_id),
    unique (user_id, project_id, source_type, source_id),
    foreign key (project_id, user_id)
        references public.projects(id, user_id) on delete cascade
);

create index idx_mindmap_source_state_project
    on public.mindmap_source_state(user_id, project_id);

create table public.library_folders (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    parent_id bigint,
    name extensions.citext not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (parent_id, user_id)
        references public.library_folders(id, user_id) on delete cascade
);

create unique index idx_library_folders_root_name
    on public.library_folders(user_id, name)
    where parent_id is null;
create unique index idx_library_folders_parent_name
    on public.library_folders(user_id, parent_id, name)
    where parent_id is not null;

create table public.library_items (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    folder_id bigint,
    item_type text not null default 'paper',
    title text not null,
    authors text,
    publication_year integer,
    source_name text,
    doi extensions.citext,
    openalex_id extensions.citext,
    url text,
    abstract text,
    original_filename text,
    file_path text,
    mime_type text,
    file_size bigint,
    status text not null default 'To read',
    personal_notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (folder_id, user_id)
        references public.library_folders(id, user_id)
        on delete set null (folder_id)
);

create unique index idx_library_items_doi
    on public.library_items(user_id, doi)
    where doi is not null and doi <> '';
create unique index idx_library_items_openalex
    on public.library_items(user_id, openalex_id)
    where openalex_id is not null and openalex_id <> '';
create index idx_library_items_folder
    on public.library_items(user_id, folder_id);

create table public.library_tags (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    name extensions.citext not null,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    unique (user_id, name)
);

create table public.library_item_tags (
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    item_id bigint not null,
    tag_id bigint not null,
    primary key (item_id, tag_id),
    foreign key (item_id, user_id)
        references public.library_items(id, user_id) on delete cascade,
    foreign key (tag_id, user_id)
        references public.library_tags(id, user_id) on delete cascade
);

create table public.library_item_projects (
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    item_id bigint not null,
    project_id bigint not null,
    primary key (item_id, project_id),
    foreign key (item_id, user_id)
        references public.library_items(id, user_id) on delete cascade,
    foreign key (project_id, user_id)
        references public.projects(id, user_id) on delete cascade
);

create table public.analysis_runs (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    library_item_id bigint,
    source_kind text not null,
    source_name text not null,
    objective text not null,
    algorithm_key text not null,
    algorithm_label text not null,
    target_column text,
    feature_columns_json jsonb not null default '[]'::jsonb,
    parameters_json jsonb not null default '{}'::jsonb,
    preprocessing_json jsonb not null default '{}'::jsonb,
    row_count integer not null default 0,
    column_count integer not null default 0,
    status text not null default 'running',
    metrics_json jsonb not null default '{}'::jsonb,
    results_json jsonb not null default '{}'::jsonb,
    predictions_file_path text,
    report_file_path text,
    error_message text,
    created_at timestamptz not null default now(),
    completed_at timestamptz,
    unique (id, user_id),
    foreign key (library_item_id, user_id)
        references public.library_items(id, user_id)
        on delete set null (library_item_id),
    check (source_kind in ('upload', 'library')),
    check (status in ('running', 'completed', 'failed'))
);

create index idx_analysis_runs_created
    on public.analysis_runs(user_id, created_at desc, id desc);
create index idx_analysis_runs_library_item
    on public.analysis_runs(user_id, library_item_id);

create table public.project_discovery_sets (
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    project_id bigint not null,
    source_mode text not null,
    profile_json jsonb not null default '{}'::jsonb,
    queries_json jsonb not null default '[]'::jsonb,
    search_options_json jsonb not null default '{}'::jsonb,
    ai_error text,
    result_count integer not null default 0,
    openalex_page integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (project_id, source_mode),
    unique (project_id, source_mode, user_id),
    foreign key (project_id, user_id)
        references public.projects(id, user_id) on delete cascade,
    check (source_mode in ('Manual Search', 'AI Recommendations'))
);

create table public.project_discovery_set_papers (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    project_id bigint not null,
    source_mode text not null,
    ranking_id text not null,
    rank_position integer not null,
    openalex_id extensions.citext,
    doi extensions.citext,
    title text not null,
    final_score double precision,
    paper_json jsonb not null,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    unique (user_id, project_id, source_mode, ranking_id),
    unique (user_id, project_id, source_mode, rank_position),
    foreign key (project_id, source_mode, user_id)
        references public.project_discovery_sets(project_id, source_mode, user_id)
        on delete cascade
);

create index idx_project_discovery_set_papers_project
    on public.project_discovery_set_papers(
        user_id,
        project_id,
        source_mode,
        rank_position
    );
create unique index idx_project_discovery_set_papers_openalex
    on public.project_discovery_set_papers(
        user_id,
        project_id,
        source_mode,
        openalex_id
    )
    where openalex_id is not null and openalex_id <> '';

create table public.manuscripts (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    project_id bigint not null,
    title text not null,
    status text not null default 'Draft',
    citation_style text not null default 'APA 7',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (project_id, user_id)
        references public.projects(id, user_id) on delete cascade,
    check (status in ('Draft', 'In review', 'Final')),
    check (citation_style in ('APA 7', 'Vancouver'))
);

create index idx_manuscripts_project
    on public.manuscripts(user_id, project_id, updated_at desc);

create table public.manuscript_sections (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    manuscript_id bigint not null,
    parent_section_id bigint,
    section_type text not null default 'custom',
    title text not null,
    content_md text not null default '',
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (manuscript_id, user_id)
        references public.manuscripts(id, user_id) on delete cascade,
    foreign key (parent_section_id, user_id)
        references public.manuscript_sections(id, user_id)
        on delete set null (parent_section_id)
);

create index idx_manuscript_sections_order
    on public.manuscript_sections(user_id, manuscript_id, sort_order, id);

create table public.manuscript_sources (
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    manuscript_id bigint not null,
    library_item_id bigint not null,
    citation_key extensions.citext not null,
    notes text,
    created_at timestamptz not null default now(),
    primary key (manuscript_id, library_item_id),
    unique (manuscript_id, library_item_id, user_id),
    unique (user_id, manuscript_id, citation_key),
    foreign key (manuscript_id, user_id)
        references public.manuscripts(id, user_id) on delete cascade,
    foreign key (library_item_id, user_id)
        references public.library_items(id, user_id) on delete cascade
);

create table public.manuscript_evidence (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    manuscript_id bigint not null,
    evidence_type text not null,
    evidence_id bigint not null,
    label text not null,
    excerpt text,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    unique (user_id, manuscript_id, evidence_type, evidence_id),
    foreign key (manuscript_id, user_id)
        references public.manuscripts(id, user_id) on delete cascade,
    check (evidence_type in ('experiment', 'summary', 'key_idea'))
);

create table public.manuscript_citations (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    manuscript_id bigint not null,
    section_id bigint not null,
    library_item_id bigint not null,
    citation_key extensions.citext not null,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    unique (user_id, section_id, library_item_id),
    foreign key (manuscript_id, user_id)
        references public.manuscripts(id, user_id) on delete cascade,
    foreign key (section_id, user_id)
        references public.manuscript_sections(id, user_id) on delete cascade,
    foreign key (manuscript_id, library_item_id, user_id)
        references public.manuscript_sources(manuscript_id, library_item_id, user_id)
        on delete cascade
);

create table public.manuscript_versions (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    manuscript_id bigint not null,
    label text not null,
    trigger_type text not null default 'manual',
    note text,
    snapshot_json jsonb not null,
    word_count integer not null default 0,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (manuscript_id, user_id)
        references public.manuscripts(id, user_id) on delete cascade
);

create index idx_manuscript_versions_created
    on public.manuscript_versions(user_id, manuscript_id, created_at desc, id desc);

create table public.manuscript_version_comments (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    version_id bigint not null,
    author_name text not null default 'Researcher',
    content text not null,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (version_id, user_id)
        references public.manuscript_versions(id, user_id) on delete cascade
);

create index idx_manuscript_version_comments
    on public.manuscript_version_comments(user_id, version_id, created_at, id);

create table public.manuscript_submission_profiles (
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    manuscript_id bigint primary key,
    target_journal text,
    journal_template text not null default 'General IMRaD',
    short_title text,
    authors_json jsonb not null default '[]'::jsonb,
    affiliations_json jsonb not null default '[]'::jsonb,
    corresponding_author_json jsonb not null default '{}'::jsonb,
    keywords_json jsonb not null default '[]'::jsonb,
    word_limit integer not null default 5000,
    abstract_word_limit integer not null default 250,
    checklist_json jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now(),
    unique (manuscript_id, user_id),
    foreign key (manuscript_id, user_id)
        references public.manuscripts(id, user_id) on delete cascade
);

create table public.manuscript_ai_messages (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    manuscript_id bigint not null,
    section_id bigint,
    role text not null,
    mode text not null,
    content text not null,
    payload_json jsonb,
    created_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (manuscript_id, user_id)
        references public.manuscripts(id, user_id) on delete cascade,
    foreign key (section_id, user_id)
        references public.manuscript_sections(id, user_id)
        on delete set null (section_id),
    check (role in ('user', 'assistant'))
);

create table public.manuscript_ai_contexts (
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    manuscript_id bigint primary key,
    context_mode text not null default 'Current section',
    section_ids_json jsonb not null default '[]'::jsonb,
    source_ids_json jsonb not null default '[]'::jsonb,
    evidence_keys_json jsonb not null default '[]'::jsonb,
    updated_at timestamptz not null default now(),
    unique (manuscript_id, user_id),
    foreign key (manuscript_id, user_id)
        references public.manuscripts(id, user_id) on delete cascade,
    check (context_mode in ('Current section', 'Whole manuscript', 'Custom'))
);

create table public.manuscript_assets (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    manuscript_id bigint not null,
    section_id bigint not null,
    asset_type text not null,
    caption text not null,
    alt_text text,
    original_filename text,
    storage_path text,
    mime_type text,
    content_json jsonb not null default '{}'::jsonb,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, user_id),
    foreign key (manuscript_id, user_id)
        references public.manuscripts(id, user_id) on delete cascade,
    foreign key (section_id, user_id)
        references public.manuscript_sections(id, user_id) on delete cascade,
    check (asset_type in ('figure', 'table', 'equation'))
);

create index idx_manuscript_assets_order
    on public.manuscript_assets(
        user_id,
        manuscript_id,
        section_id,
        sort_order,
        id
    );

create table app_private.usage_counters (
    resource text not null,
    principal text not null,
    window_seconds integer not null,
    window_start bigint not null,
    request_count integer not null,
    primary key (resource, principal, window_seconds, window_start)
);

create table app_private.resource_leases (
    resource text not null,
    lease_id uuid primary key,
    principal text not null,
    expires_at bigint not null
);

create index resource_leases_resource_expiry
    on app_private.resource_leases(resource, expires_at);

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'projects',
        'chats',
        'messages',
        'experiment_ai_messages',
        'audio_records',
        'summaries',
        'project_ideas',
        'mindmap_nodes',
        'mindmap_edges',
        'mindmap_source_state',
        'library_folders',
        'library_items',
        'library_tags',
        'library_item_tags',
        'library_item_projects',
        'analysis_runs',
        'project_discovery_sets',
        'project_discovery_set_papers',
        'manuscripts',
        'manuscript_sections',
        'manuscript_sources',
        'manuscript_evidence',
        'manuscript_citations',
        'manuscript_versions',
        'manuscript_version_comments',
        'manuscript_submission_profiles',
        'manuscript_ai_messages',
        'manuscript_ai_contexts',
        'manuscript_assets'
    ]
    loop
        execute format('alter table public.%I enable row level security', table_name);
        execute format('alter table public.%I force row level security', table_name);
        execute format(
            'create policy %I on public.%I for all to authenticated '
            || 'using (user_id = app_private.current_app_user_id()) '
            || 'with check (user_id = app_private.current_app_user_id())',
            table_name || '_owner_access',
            table_name
        );
        execute format('revoke all on table public.%I from anon', table_name);
        execute format('revoke all on table public.%I from authenticated', table_name);
        execute format(
            'grant select, insert, update, delete on table public.%I to authenticated',
            table_name
        );
    end loop;
end;
$$;

revoke all on all sequences in schema public from anon;
grant usage, select on all sequences in schema public to authenticated;

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'library_folders',
        'library_items',
        'project_discovery_sets',
        'manuscripts',
        'manuscript_sections',
        'manuscript_submission_profiles',
        'manuscript_ai_contexts',
        'manuscript_assets'
    ]
    loop
        execute format(
            'create trigger %I before update on public.%I '
            || 'for each row execute function app_private.set_updated_at()',
            table_name || '_set_updated_at',
            table_name
        );
    end loop;
end;
$$;
