create table public.calendar_reminders (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    title text not null,
    reminder_at timestamp without time zone not null,
    notes text,
    completed integer not null default 0,
    notified_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, user_id),
    check (char_length(btrim(title)) between 1 and 160),
    check (notes is null or char_length(notes) <= 2000),
    check (completed in (0, 1))
);

create index idx_calendar_reminders_due
    on public.calendar_reminders(user_id, completed, reminder_at);

alter table public.calendar_reminders enable row level security;
alter table public.calendar_reminders force row level security;

create policy calendar_reminders_owner_access
    on public.calendar_reminders
    for all
    to authenticated
    using (user_id = (select app_private.current_app_user_id()))
    with check (user_id = (select app_private.current_app_user_id()));

revoke all on table public.calendar_reminders from anon;
revoke all on table public.calendar_reminders from authenticated;
grant select, insert, update, delete
    on table public.calendar_reminders
    to authenticated;
grant usage, select on sequence public.calendar_reminders_id_seq to authenticated;

create trigger calendar_reminders_set_updated_at
    before update on public.calendar_reminders
    for each row execute function app_private.set_updated_at();
