create table public.research_cases (
    id bigint generated by default as identity primary key,
    user_id uuid not null default app_private.current_app_user_id()
        references public.app_users(id) on delete cascade,
    project_id bigint not null,
    library_item_id bigint not null,
    schema_version text not null,
    prompt_version text not null,
    source_hash text not null,
    semantic_json jsonb not null default '{}'::jsonb,
    embedding_json jsonb not null default '[]'::jsonb,
    embedding_model text not null,
    generation_model text not null,
    status text not null default 'processing',
    error_message text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, user_id),
    unique (user_id, project_id, library_item_id),
    foreign key (project_id, user_id)
        references public.projects(id, user_id) on delete cascade,
    foreign key (library_item_id, user_id)
        references public.library_items(id, user_id) on delete cascade,
    foreign key (library_item_id, project_id)
        references public.library_item_projects(item_id, project_id)
        on delete cascade,
    check (status in ('processing', 'ready', 'failed'))
);

create index idx_research_cases_project_status
    on public.research_cases(user_id, project_id, status, updated_at desc);

alter table public.research_cases enable row level security;
alter table public.research_cases force row level security;

create policy research_cases_owner_access
    on public.research_cases
    for all
    to authenticated
    using (user_id = (select app_private.current_app_user_id()))
    with check (user_id = (select app_private.current_app_user_id()));

revoke all on table public.research_cases from anon;
revoke all on table public.research_cases from authenticated;
grant select, insert, update, delete
    on table public.research_cases
    to authenticated;
grant usage, select on sequence public.research_cases_id_seq to authenticated;

create trigger research_cases_set_updated_at
    before update on public.research_cases
    for each row execute function app_private.set_updated_at();
